### ISSUE TITLE
Problem using output in a pipeline

### ISSUE THREAD

**Issue by pauldougan** [AP-Hunt/cf-traverse#13]
I am using the plugin to look at the redis plans

`cf traverse service_offering instances_of redis`

which works as expected, however when attempting to pipe the stdout into another process the data is not there

```
cf traverse service_offering instances_of redis > foo.txt
wc -l foo.txt
 0 foo.txt
```

```
cf traverse service_offering instances_of redis  2> foo.txt
(venv) GDS3821:cf-traverse pauldougan$ wc -l foo.txt
19793 foo.txt
```
looks like the output is going to `stderr`

**Comment by AP-Hunt** [comment]
Thanks, Paul. I hadn't noticed that! Resolved in [release 0.7.0](https://github.com/AP-Hunt/cf-traverse/releases/tag/0.7.0)
